### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ChildishGiant** [milkytracker/MilkyTracker#215]
http://milkytracker.github.io/ and https://milkytracker.titandemo.org/ (where it leads) are down

**Comment by dwhinham** [comment]
Thanks for letting us know.

milkytracker.org was a redirect to milkytracker.titandemo.org, and that was pointing at the GitHub Pages DNS.
It looks like titandemo.org is having issues.

What I've done is updated the milkytracker.org's A records to point to GItHub Pages DNS, so that milkytracker.org will be the correct URL from now on.

We did the titandemo.org stuff because we lost control of the milkytracker.org domain for a while, but now we have it back we can use it as the primary URL.

So:
- Let's wait for DNS records to propagate and milkytracker.org should be back up shortly.
- We need to tell the titandemo.org guys to update their DNS to just redirect to milkytracker.org when it's back up.

**Comment by sagamusix** [comment]
Seems like titandemo.org is up again, so it should now be changed to redirect instead of directly point to GitHub Pages (which now results in a certificate warning).

**Comment by dwhinham** [comment]
Huh; I was told this had been done :)

I'll give Titan a nudge again - cheers!

**Comment by dwhinham** [comment]
Fixed.
