### ISSUE TITLE
Enable note off with '1' key in Windows

### ISSUE THREAD

**Issue by akciom** [milkytracker/MilkyTracker#228]
In OS X and Linux the '1' key can be used to enter the note off key where as in Windows that key has been actively disabled with an ifndef block leaving the Caps Lock key as the only option.

Is there any technical reason why it's been disabled in Windows? I couldn't find any but I only took cursory look.

The ifndef in question:

https://github.com/milkytracker/MilkyTracker/blob/3d4dfac5d25ff4c7efb769a887d4918571804aa9/src/tracker/PatternEditorControlKeyboard.cpp#L543

**Comment by Deltafire** [comment]
I think the 1 key was added later, due to difficulty reading the caps-lock key on non-Windows platforms.

I don't see any reason why it should be disabled for Windows, so I've removed the #ifndef guard. There's an automated build on [appveyor](https://ci.appveyor.com/project/Deltafire/milkytracker) if you want to test it out (under 'artifacts').

**Comment by akciom** [comment]
It seems to work just fine. Thank you.
