### ISSUE TITLE
Loading error when attempting to load >32 channel IT files

### ISSUE THREAD

**Issue by alugarius** [milkytracker/MilkyTracker#66]
I have a IT file, VLC and SchismTracker do play them
here an example file! [chount.zip](https://github.com/milkytracker/MilkyTracker/files/831822/chount.zip)

please fix it

**Comment by Deltafire** [comment]
In order to maintain compatibility with FT2, MilkyTracker has a 32-channel limit.  chount.zip contains a 64-channel IT file.

Ideally a dialog box should be displayed describing this error; however this would require some restructuring of the code - I'd be happy to accept a patch for this but don't have time myself.

**Comment by alugarius** [comment]
I saw another thread, similar to this.
Im closing this one
